package com.brasil.transparente.processor.util.estados;

import lombok.Getter;

@Getter
public final class RSConstants {

    public static final String INSTITUTO_RIOGRANDENSE_ARROZ = "INSTITUTO RIOGRANDENSE DO ARROZ";
    public static final String UERGS = "UNIVERSIDADE ESTADUAL DO RIO GRANDE DO SUL";
    public static final String FUNDACAO_ESCOLA_LIBERATO = "FUNDACAO ESCOLA TECNICA LIBERATO SALZANO VIEIRA DA CUNHA";
    public static final String FUNDACAO_AMPARO_PESQUISA = "FUNDACAO DE AMPARO A PESQUISA DO ESTADO DO RIO GRANDE DO SUL";
    public static final String FUNDACAO_PROTECAO_AMBIENTAL_ROESSLER = "FUNDACAO ESTADUAL DE PROTECAO AMBIENTAL HENRIQUE LUIS ROESSLER";
    public static final String ESCRITORIO_DESENVOLVIMENTO_PROJETOS = "ESCRITORIO DE DESENVOLVIMENTO DE PROJETOS";
    public static final String FUNDACAO_PLANEJAMENTO_METROPOLITANO_REGIONAL = "FUNDACAO ESTADUAL DE PLANEJAMENTO METROPOLITANO E REGIONAL";
    public static final String FUDACAO_ATENDIMENTO_SOCIO_EDUCATIVO = "FUNDACAO DE ATENDIMENTO SOCIO-EDUCATIVO DO RIO GRANDE DO SUL";
    public static final String FUNDACAO_PROTECAO_ESPECIAL = "FUNDACAO DE PROTECAO ESPECIAL DO RIO GRANDE DO SUL";
    public static final String FUNDACAO_GAUCHA_TRABALHO_ACAO_SOCIAL = "FUNDACAO GAUCHA DO TRABALHO E ACAO SOCIAL";
    public static final String FUNDACAO_PPD_PPAH = "FUNDACAO DE ARTICULACAO E DESENVOLVIMENTO DE POLITICAS PUBLICAS PARA PPD E PPAH";
    public static final String FUNDACAO_ORQUESTRA = "FUNDACAO ORQUESTRA SINFONICA DE PORTO ALEGRE";
    public static final String FUNDACAO_TEATRO = "FUNDACAO TEATRO SAO PEDRO";
    public static final String DEPARTAMENTO_ESTADUAL_TRANSITO = "DEPARTAMENTO ESTADUAL DE TRANSITO";
    public static final String DEPARTAMENTO_ESTRADAS_RODAGEM = "DEPARTAMENTO AUTONOMO DE ESTRADAS DE RODAGEM";
    public static final String JUNTA_COMERCIAL = "JUNTA COMERCIAL, INDUSTRIAL E SERVICOS DO RIO GRANDE DO SUL";
    public static final String AGENCIA_DELEGADOS = "AGENCIA ESTADUAL DE REGULACAO DOS SERVICOS PUBLICOS DELEGADOS DO RS";
    public static final String INSTITUTO_PREVIDENCIA = "INSTITUTO DE PREVIDENCIA DO ESTADO DO RIO GRANDE DO SUL";
    public static final String INSTITUTO_ASSISTENCIA_SAUDE_SERVIDORES = "INSTITUTO DE ASSISTENCIA A SAUDE DOS SERVIDORES PUBLICOS DO RIO GRANDE DO SUL";
    public static final String CONSELHO_EDUCACAO = "CONSELHO ESTADUAL DE EDUCACAO";
    public static final String ENCARGOS_FINANCEIROS = "ENCARGOS FINANCEIROS DO ESTADO";

    public static final String SECRETARIA_AGRICULTURA = "SECRETARIA DA AGRICULTURA, PECUARIA, PRODUCAO SUSTENTAVEL E IRRIGACAO";
    public static final String SECRETARIA_EDUCACAO = "SECRETARIA DA EDUCACAO";
    public static final String SECRETARIA_INOVACAO = "SECRETARIA DE INOVACAO, CIENCIA E TECNOLOGIA";
    public static final String SECRETARIA_MEIO_AMBIENTE = "SECRETARIA DO MEIO AMBIENTE E INFRAESTRUTURA";
    public static final String SECRETARIA_PLANEJAMENTO = "SECRETARIA DE PLANEJAMENTO, GOVERNANCA E GESTAO";
    public static final String SECRETARIA_DESENVOLVIMENTO_SOCIAL = "SECRETARIA DE DESENVOLVIMENTO SOCIAL";
    public static final String SECRETARIA_CULTURA = "SECRETARIA DA CULTURA";
    public static final String SECRETARIA_SEGURANCA_PUBLICA = "SECRETARIA DA SEGURANCA PUBLICA";
    public static final String SECRETARIA_LOGISTICA_TRANSPORTES = "SECRETARIA DE LOGISTICA E TRANSPORTES";
    public static final String SECRETARIA_DESENVOLVIMENTO_ECONOMICO = "SECRETARIA DE DESENVOLVIMENTO ECONOMICO";
    public static final String SECRETARIA_PARCERIAS_CONCESSOES = "SECRETARIA DE PARCERIAS E CONCESSOES";
    public static final String SECRETARIA_FAZENDA = "SECRETARIA DA FAZENDA";

}
